[package]
name = "tarmg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmder = "0.5"
toml = "0.5"
tar_script = { path = "../tar_script" }